-- CREAR TAULA FILMS (EN CAS DE QUE NO ESTIGUI CREADA)
CREATE TABLE films (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    director VARCHAR(255),
    year INT,
    description VARCHAR(255),
    genre VARCHAR(20),
    duration INT,
    cast VARCHAR(100)
);

-- ALTER TABLE (SI NOMES VOLEM AFEGIR ELS NOUS CAMPS)
/*
ALTER TABLE films
ADD COLUMN description VARCHAR(255),
ADD COLUMN genre VARCHAR(20),
ADD COLUMN duration INT,
ADD COLUMN cast VARCHAR(100);
*/

-- CREAR TAULA GAMES (EN CAS DE QUE NO ESTIGUI CREADA)
CREATE TABLE games (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    developers VARCHAR(255),
    year INT,
    genre VARCHAR(20),
    description VARCHAR(255),
);
